name: megamouth
dependencies:
- appnope=0.1.0=py35_0
- backports=1.0=py35_0
- decorator=4.0.9=py35_0
- get_terminal_size=1.0.0=py35_0
- ipython=4.2.0=py35_1
- ipython_genutils=0.1.0=py35_0
- libxml2=2.9.2=0
- libxslt=1.1.28=2
- lxml=3.6.0=py35_0
- openssl=1.0.2h=1
- path.py=8.2.1=py35_0
- pexpect=4.0.1=py35_0
- pickleshare=0.7.2=py35_0
- pip=8.1.1=py35_1
- ptyprocess=0.5.1=py35_0
- python=3.5.1=0
- python.app=1.2=py35_4
- readline=6.2=2
- requests=2.10.0=py35_0
- setuptools=21.2.1=py35_0
- simplegeneric=0.8.1=py35_1
- sqlite=3.13.0=0
- tk=8.5.18=0
- traitlets=4.2.1=py35_0
- wheel=0.29.0=py35_0
- xz=5.0.5=1
- zlib=1.2.8=3
- pip:
  - argh==0.26.2
  - backports.shutil-get-terminal-size==1.0.0
  - ipython-genutils==0.1.0

